export const COMM_AGENDA_ITEM_ADDED = "COMM.AGENDA_ITEM_ADDED" as const;
export const COMM_AGENDA_ITEM_UPDATED = "COMM.AGENDA_ITEM_UPDATED" as const;
export const COMM_AGENDA_ITEM_REMOVED = "COMM.AGENDA_ITEM_REMOVED" as const;
