export const COMM_ATTENDEE_ADDED = "COMM.ATTENDEE_ADDED" as const;
export const COMM_ATTENDEE_UPDATED = "COMM.ATTENDEE_UPDATED" as const;
export const COMM_ATTENDEE_STATUS_UPDATED = "COMM.ATTENDEE_STATUS_UPDATED" as const;
export const COMM_ATTENDEE_REMOVED = "COMM.ATTENDEE_REMOVED" as const;
