export const COMM_MEETING_CREATED = "COMM.MEETING_CREATED" as const;
export const COMM_MEETING_UPDATED = "COMM.MEETING_UPDATED" as const;
export const COMM_MEETING_DELETED = "COMM.MEETING_DELETED" as const;
export const COMM_MEETING_STARTED = "COMM.MEETING_STARTED" as const;
export const COMM_MEETING_ADJOURNED = "COMM.MEETING_ADJOURNED" as const;
export const COMM_MEETING_CANCELLED = "COMM.MEETING_CANCELLED" as const;
export const COMM_MEETING_COMPLETED = "COMM.MEETING_COMPLETED" as const;
