export const COMM_MINUTES_RECORDED = "COMM.MINUTES_RECORDED" as const;
export const COMM_ACTION_ITEM_CREATED = "COMM.ACTION_ITEM_CREATED" as const;
export const COMM_ACTION_ITEM_UPDATED = "COMM.ACTION_ITEM_UPDATED" as const;
export const COMM_ACTION_ITEM_DELETED = "COMM.ACTION_ITEM_DELETED" as const;
