export const COMM_RESOLUTION_PROPOSED = "COMM.RESOLUTION_PROPOSED" as const;
export const COMM_RESOLUTION_UPDATED = "COMM.RESOLUTION_UPDATED" as const;
export const COMM_RESOLUTION_WITHDRAWN = "COMM.RESOLUTION_WITHDRAWN" as const;
export const COMM_VOTE_CAST = "COMM.VOTE_CAST" as const;
