export const COMM_DOCUMENT_CREATED = "COMM.DOCUMENT_CREATED" as const;
export const COMM_DOCUMENT_UPDATED = "COMM.DOCUMENT_UPDATED" as const;
export const COMM_DOCUMENT_PUBLISHED = "COMM.DOCUMENT_PUBLISHED" as const;
export const COMM_DOCUMENT_ARCHIVED = "COMM.DOCUMENT_ARCHIVED" as const;
export const COMM_DOCUMENT_COLLABORATOR_ADDED = "COMM.DOCUMENT_COLLABORATOR_ADDED" as const;
export const COMM_DOCUMENT_COLLABORATOR_REMOVED = "COMM.DOCUMENT_COLLABORATOR_REMOVED" as const;
