export const COMM_APPROVAL_REQUEST_CREATED = "COMM.APPROVAL_REQUEST_CREATED" as const;
export const COMM_APPROVAL_STEP_APPROVED = "COMM.APPROVAL_STEP_APPROVED" as const;
export const COMM_APPROVAL_STEP_REJECTED = "COMM.APPROVAL_STEP_REJECTED" as const;
export const COMM_APPROVAL_STEP_DELEGATED = "COMM.APPROVAL_STEP_DELEGATED" as const;
export const COMM_APPROVAL_ESCALATED = "COMM.APPROVAL_ESCALATED" as const;
export const COMM_APPROVAL_WITHDRAWN = "COMM.APPROVAL_WITHDRAWN" as const;
export const COMM_APPROVAL_POLICY_CREATED = "COMM.APPROVAL_POLICY_CREATED" as const;
export const COMM_APPROVAL_DELEGATION_SET = "COMM.APPROVAL_DELEGATION_SET" as const;

export const ApprovalEventTypes = [
  COMM_APPROVAL_REQUEST_CREATED,
  COMM_APPROVAL_STEP_APPROVED,
  COMM_APPROVAL_STEP_REJECTED,
  COMM_APPROVAL_STEP_DELEGATED,
  COMM_APPROVAL_ESCALATED,
  COMM_APPROVAL_WITHDRAWN,
  COMM_APPROVAL_POLICY_CREATED,
  COMM_APPROVAL_DELEGATION_SET,
] as const;
