/**
 * AP (Accounts Payable) error codes.
 *
 * RULES:
 *   1. All codes prefixed with AP_
 *   2. Naming convention: AP_NOUN_REASON (SCREAMING_SNAKE_CASE)
 *   3. Removing or renaming a code is a BREAKING CHANGE
 */
import { z } from "zod";

// ─── AP Invoice Error Codes ───────────────────────────────────────────────────
export const AP_INVOICE_NOT_FOUND = "AP_INVOICE_NOT_FOUND" as const;
export const AP_INVOICE_ALREADY_APPROVED = "AP_INVOICE_ALREADY_APPROVED" as const;
export const AP_INVOICE_ALREADY_POSTED = "AP_INVOICE_ALREADY_POSTED" as const;
export const AP_INVOICE_ALREADY_VOIDED = "AP_INVOICE_ALREADY_VOIDED" as const;
export const AP_INVOICE_ALREADY_PAID = "AP_INVOICE_ALREADY_PAID" as const;
export const AP_INVOICE_INVALID_STATUS_TRANSITION = "AP_INVOICE_INVALID_STATUS_TRANSITION" as const;
export const AP_INVOICE_HAS_ACTIVE_HOLDS = "AP_INVOICE_HAS_ACTIVE_HOLDS" as const;

// ─── AP Payment Terms Error Codes ─────────────────────────────────────────────
export const AP_PAYMENT_TERMS_NOT_FOUND = "AP_PAYMENT_TERMS_NOT_FOUND" as const;
export const AP_PAYMENT_TERMS_CODE_EXISTS = "AP_PAYMENT_TERMS_CODE_EXISTS" as const;

// ─── AP Hold Error Codes ──────────────────────────────────────────────────────
export const AP_HOLD_NOT_FOUND = "AP_HOLD_NOT_FOUND" as const;
export const AP_HOLD_ALREADY_RELEASED = "AP_HOLD_ALREADY_RELEASED" as const;

// ─── AP Invoice Line Error Codes ──────────────────────────────────────────────
export const AP_INVOICE_LINE_NOT_FOUND = "AP_INVOICE_LINE_NOT_FOUND" as const;
export const AP_INVOICE_LINE_DUPLICATE_NUMBER = "AP_INVOICE_LINE_DUPLICATE_NUMBER" as const;

// ─── AP Payment Run Error Codes ───────────────────────────────────────────────
export const AP_PAYMENT_RUN_NOT_FOUND = "AP_PAYMENT_RUN_NOT_FOUND" as const;
export const AP_PAYMENT_RUN_NOT_DRAFT = "AP_PAYMENT_RUN_NOT_DRAFT" as const;
export const AP_PAYMENT_RUN_ALREADY_APPROVED = "AP_PAYMENT_RUN_ALREADY_APPROVED" as const;
export const AP_PAYMENT_RUN_ALREADY_EXECUTED = "AP_PAYMENT_RUN_ALREADY_EXECUTED" as const;
export const AP_PAYMENT_RUN_ALREADY_CANCELLED = "AP_PAYMENT_RUN_ALREADY_CANCELLED" as const;
export const AP_PAYMENT_RUN_EMPTY = "AP_PAYMENT_RUN_EMPTY" as const;
export const AP_PAYMENT_RUN_CURRENCY_MISMATCH = "AP_PAYMENT_RUN_CURRENCY_MISMATCH" as const;

// ─── AP Payment Run Item Error Codes ──────────────────────────────────────────
export const AP_PAYMENT_RUN_ITEM_NOT_FOUND = "AP_PAYMENT_RUN_ITEM_NOT_FOUND" as const;
export const AP_PAYMENT_RUN_ITEM_DUPLICATE_INVOICE =
  "AP_PAYMENT_RUN_ITEM_DUPLICATE_INVOICE" as const;
export const AP_PAYMENT_RUN_ITEM_INVOICE_NOT_PAYABLE =
  "AP_PAYMENT_RUN_ITEM_INVOICE_NOT_PAYABLE" as const;
export const AP_PAYMENT_RUN_ITEM_AMOUNT_EXCEEDS_BALANCE =
  "AP_PAYMENT_RUN_ITEM_AMOUNT_EXCEEDS_BALANCE" as const;
export const AP_SUPPLIER_BANK_ACCOUNT_MISSING = "AP_SUPPLIER_BANK_ACCOUNT_MISSING" as const;

// ─── AP Prepayment Error Codes ────────────────────────────────────────────────
export const AP_PREPAYMENT_NOT_FOUND = "AP_PREPAYMENT_NOT_FOUND" as const;
export const AP_PREPAYMENT_NUMBER_EXISTS = "AP_PREPAYMENT_NUMBER_EXISTS" as const;
export const AP_PREPAYMENT_INSUFFICIENT_BALANCE = "AP_PREPAYMENT_INSUFFICIENT_BALANCE" as const;
export const AP_PREPAYMENT_ALREADY_VOIDED = "AP_PREPAYMENT_ALREADY_VOIDED" as const;
export const AP_PREPAYMENT_CURRENCY_MISMATCH = "AP_PREPAYMENT_CURRENCY_MISMATCH" as const;
export const AP_PREPAYMENT_SUPPLIER_MISMATCH = "AP_PREPAYMENT_SUPPLIER_MISMATCH" as const;
export const AP_PREPAYMENT_APPLICATION_NOT_FOUND = "AP_PREPAYMENT_APPLICATION_NOT_FOUND" as const;

// ─── AP Match Tolerance Error Codes ───────────────────────────────────────────
export const AP_MATCH_TOLERANCE_NOT_FOUND = "AP_MATCH_TOLERANCE_NOT_FOUND" as const;
export const AP_MATCH_TOLERANCE_DUPLICATE_SCOPE = "AP_MATCH_TOLERANCE_DUPLICATE_SCOPE" as const;
export const AP_MATCH_TOLERANCE_OVER_VARIANCE = "AP_MATCH_TOLERANCE_OVER_VARIANCE" as const;

// ─── AP WHT Certificate Error Codes ───────────────────────────────────────────
export const AP_WHT_CERTIFICATE_NOT_FOUND = "AP_WHT_CERTIFICATE_NOT_FOUND" as const;
export const AP_WHT_CERTIFICATE_NUMBER_EXISTS = "AP_WHT_CERTIFICATE_NUMBER_EXISTS" as const;
export const AP_WHT_CERTIFICATE_ALREADY_ISSUED = "AP_WHT_CERTIFICATE_ALREADY_ISSUED" as const;
export const AP_WHT_CERTIFICATE_ALREADY_SUBMITTED = "AP_WHT_CERTIFICATE_ALREADY_SUBMITTED" as const;
export const AP_WHT_CERTIFICATE_ALREADY_VOIDED = "AP_WHT_CERTIFICATE_ALREADY_VOIDED" as const;
export const AP_WHT_EXEMPTION_NOT_FOUND = "AP_WHT_EXEMPTION_NOT_FOUND" as const;
export const AP_WHT_EXEMPTION_EXPIRED = "AP_WHT_EXEMPTION_EXPIRED" as const;

// ─── AP Error Code Array ──────────────────────────────────────────────────────
export const ApErrorCodeValues = [
  // Invoice
  AP_INVOICE_NOT_FOUND,
  AP_INVOICE_ALREADY_APPROVED,
  AP_INVOICE_ALREADY_POSTED,
  AP_INVOICE_ALREADY_VOIDED,
  AP_INVOICE_ALREADY_PAID,
  AP_INVOICE_INVALID_STATUS_TRANSITION,
  AP_INVOICE_HAS_ACTIVE_HOLDS,

  // Payment Terms
  AP_PAYMENT_TERMS_NOT_FOUND,
  AP_PAYMENT_TERMS_CODE_EXISTS,

  // Holds
  AP_HOLD_NOT_FOUND,
  AP_HOLD_ALREADY_RELEASED,

  // Invoice Lines
  AP_INVOICE_LINE_NOT_FOUND,
  AP_INVOICE_LINE_DUPLICATE_NUMBER,

  // Payment Runs
  AP_PAYMENT_RUN_NOT_FOUND,
  AP_PAYMENT_RUN_NOT_DRAFT,
  AP_PAYMENT_RUN_ALREADY_APPROVED,
  AP_PAYMENT_RUN_ALREADY_EXECUTED,
  AP_PAYMENT_RUN_ALREADY_CANCELLED,
  AP_PAYMENT_RUN_EMPTY,
  AP_PAYMENT_RUN_CURRENCY_MISMATCH,

  // Payment Run Items
  AP_PAYMENT_RUN_ITEM_NOT_FOUND,
  AP_PAYMENT_RUN_ITEM_DUPLICATE_INVOICE,
  AP_PAYMENT_RUN_ITEM_INVOICE_NOT_PAYABLE,
  AP_PAYMENT_RUN_ITEM_AMOUNT_EXCEEDS_BALANCE,
  AP_SUPPLIER_BANK_ACCOUNT_MISSING,

  // Prepayments
  AP_PREPAYMENT_NOT_FOUND,
  AP_PREPAYMENT_NUMBER_EXISTS,
  AP_PREPAYMENT_INSUFFICIENT_BALANCE,
  AP_PREPAYMENT_ALREADY_VOIDED,
  AP_PREPAYMENT_CURRENCY_MISMATCH,
  AP_PREPAYMENT_SUPPLIER_MISMATCH,
  AP_PREPAYMENT_APPLICATION_NOT_FOUND,

  // Match Tolerances
  AP_MATCH_TOLERANCE_NOT_FOUND,
  AP_MATCH_TOLERANCE_DUPLICATE_SCOPE,
  AP_MATCH_TOLERANCE_OVER_VARIANCE,

  // WHT Certificates
  AP_WHT_CERTIFICATE_NOT_FOUND,
  AP_WHT_CERTIFICATE_NUMBER_EXISTS,
  AP_WHT_CERTIFICATE_ALREADY_ISSUED,
  AP_WHT_CERTIFICATE_ALREADY_SUBMITTED,
  AP_WHT_CERTIFICATE_ALREADY_VOIDED,
  AP_WHT_EXEMPTION_NOT_FOUND,
  AP_WHT_EXEMPTION_EXPIRED,
] as const;

export const ApErrorCodeSchema = z.enum(ApErrorCodeValues);
export type ApErrorCode = z.infer<typeof ApErrorCodeSchema>;
