export const HRM_EVENTS = {
  PERSON_CREATED: "hrm.person.created",
  EMPLOYEE_HIRED: "hrm.employee.hired",
  EMPLOYEE_TRANSFERRED: "hrm.employee.transferred",
  EMPLOYEE_PROMOTED: "hrm.employee.promoted",
  EMPLOYMENT_CONTRACT_ADDED: "hrm.employment.contract.added",
  EMPLOYMENT_TERMS_CHANGED: "hrm.employment.terms.changed",
  EMPLOYEE_TERMINATED: "hrm.employee.terminated",
  EMPLOYEE_SUSPENDED: "hrm.employee.suspended",
  EMPLOYEE_RESUMED: "hrm.employee.resumed",
  EMPLOYEE_REHIRED: "hrm.employee.rehired",
  PERSON_IDENTITY_RECORDED: "hrm.person.identity.recorded",
  PERSON_ADDRESS_ADDED: "hrm.person.address.added",
  EMERGENCY_CONTACT_ADDED: "hrm.emergency-contact.added",
  DEPENDENT_ADDED: "hrm.dependent.added",
  EMPLOYEE_DOCUMENT_ADDED: "hrm.employee-document.added",
  ORG_UNIT_CREATED: "hrm.org-unit.created",
  JOB_CREATED: "hrm.job.created",
  GRADE_CREATED: "hrm.grade.created",
  POSITION_CREATED: "hrm.position.created",
  POSITION_CLOSED: "hrm.position.closed",
  REQUISITION_CREATED: "hrm.requisition.created",
  REQUISITION_APPROVED: "hrm.requisition.approved",
  CANDIDATE_CREATED: "hrm.candidate.created",
  APPLICATION_SUBMITTED: "hrm.application.submitted",
  INTERVIEW_SCHEDULED: "hrm.interview.scheduled",
  INTERVIEW_FEEDBACK_SUBMITTED: "hrm.interview-feedback.submitted",
  OFFER_ISSUED: "hrm.offer.issued",
  OFFER_ACCEPTED: "hrm.offer.accepted",
  ONBOARDING_STARTED: "hrm.onboarding.started",
  ONBOARDING_TASK_COMPLETED: "hrm.onboarding-task.completed",
  PROBATION_REVIEW_RECORDED: "hrm.probation.review.recorded",
  SEPARATION_STARTED: "hrm.separation.started",
  EXIT_ITEM_CLEARED: "hrm.exit-item.cleared",
  SEPARATION_FINALIZED: "hrm.separation.finalized",
  ATTENDANCE_RECORDED: "hrm.attendance.recorded",
  ROSTER_ASSIGNMENT_CREATED: "hrm.roster-assignment.created",
  LEAVE_REQUEST_CREATED: "hrm.leave.request.created",
  LEAVE_REQUEST_REVIEWED: "hrm.leave.request.reviewed",
  LEAVE_BALANCE_RECALCULATED: "hrm.leave.balance.recalculated",
  COMPENSATION_STRUCTURE_CREATED: "hrm.compensation.structure.created",
  COMPENSATION_PACKAGE_ASSIGNED: "hrm.compensation.package.assigned",
  SALARY_CHANGE_PROCESSED: "hrm.compensation.salary.changed",
  BENEFIT_PLAN_CREATED: "hrm.benefit.plan.created",
  BENEFIT_ENROLLED: "hrm.benefit.enrolled",
  PAYROLL_PERIOD_OPENED: "hrm.payroll.period.opened",
  PAYROLL_PERIOD_LOCKED: "hrm.payroll.period.locked",
  PAYROLL_RUN_CREATED: "hrm.payroll.run.created",
  PAYROLL_RUN_SUBMITTED: "hrm.payroll.run.submitted",
  PAYROLL_RUN_APPROVED: "hrm.payroll.run.approved",
  PAYSLIPS_PUBLISHED: "hrm.payslips.published",
  PAYMENT_BATCH_GENERATED: "hrm.payment.batch.generated",
  PAYROLL_POSTED_TO_GL: "hrm.payroll.posted.to.gl",
  REVIEW_CYCLE_CREATED: "hrm.review-cycle.created",
  PERFORMANCE_REVIEW_CREATED: "hrm.performance-review.created",
  SELF_REVIEW_SUBMITTED: "hrm.self-review.submitted",
  MANAGER_REVIEW_COMPLETED: "hrm.manager-review.completed",
  PERFORMANCE_GOAL_CREATED: "hrm.performance-goal.created",
  TALENT_PROFILE_CREATED: "hrm.talent-profile.created",
  SUCCESSION_PLAN_CREATED: "hrm.succession-plan.created",
  SUCCESSOR_NOMINATED: "hrm.successor.nominated",
  COURSE_CREATED: "hrm.course.created",
  COURSE_SESSION_CREATED: "hrm.course-session.created",
  LEARNER_ENROLLED: "hrm.learner.enrolled",
  ENROLLMENT_COMPLETED: "hrm.enrollment.completed",
  CERTIFICATION_RECORDED: "hrm.certification.recorded",
  POLICY_DOCUMENT_CREATED: "hrm.policy-document.created",
  POLICY_ACKNOWLEDGED: "hrm.policy.acknowledged",
  COMPLIANCE_CHECK_CREATED: "hrm.compliance-check.created",
  WORK_PERMIT_RECORDED: "hrm.work-permit.recorded",
  GRIEVANCE_CASE_CREATED: "hrm.grievance-case.created",
  GRIEVANCE_CASE_CLOSED: "hrm.grievance-case.closed",
  DISCIPLINARY_ACTION_CREATED: "hrm.disciplinary-action.created",
  DISCIPLINARY_ACTION_CLOSED: "hrm.disciplinary-action.closed",
  CASE_EVIDENCE_ATTACHED: "hrm.case-evidence.attached",
  WORKFORCE_PLAN_CREATED: "hrm.workforce-plan.created",
  WORKFORCE_SCENARIO_CREATED: "hrm.workforce-scenario.created",
  POSITION_BUDGET_SET: "hrm.position-budget.set",
  HIRING_FORECAST_CREATED: "hrm.hiring-forecast.created",
} as const;

export type HrmEventName = (typeof HRM_EVENTS)[keyof typeof HRM_EVENTS];

export interface HrmDomainEvent<TPayload = Record<string, unknown>> {
  eventName: HrmEventName;
  orgId: string;
  aggregateType: string;
  aggregateId: string;
  payload: TPayload;
  occurredAt: string;
  actorUserId: string;
  correlationId?: string | null;
  idempotencyKey?: string | null;
}
