export const COMM_PROJECT_CREATED = "COMM.PROJECT_CREATED" as const;
export const COMM_PROJECT_UPDATED = "COMM.PROJECT_UPDATED" as const;
export const COMM_PROJECT_STATUS_CHANGED = "COMM.PROJECT_STATUS_CHANGED" as const;
export const COMM_PROJECT_ARCHIVED = "COMM.PROJECT_ARCHIVED" as const;
export const COMM_PROJECT_DELETED = "COMM.PROJECT_DELETED" as const;
export const COMM_PROJECT_MEMBER_ADDED = "COMM.PROJECT_MEMBER_ADDED" as const;
export const COMM_PROJECT_MEMBER_REMOVED = "COMM.PROJECT_MEMBER_REMOVED" as const;
export const COMM_PROJECT_MILESTONE_CREATED = "COMM.PROJECT_MILESTONE_CREATED" as const;
export const COMM_PROJECT_MILESTONE_COMPLETED = "COMM.PROJECT_MILESTONE_COMPLETED" as const;

export const ProjectEventTypes = [
  COMM_PROJECT_CREATED,
  COMM_PROJECT_UPDATED,
  COMM_PROJECT_STATUS_CHANGED,
  COMM_PROJECT_ARCHIVED,
  COMM_PROJECT_DELETED,
  COMM_PROJECT_MEMBER_ADDED,
  COMM_PROJECT_MEMBER_REMOVED,
  COMM_PROJECT_MILESTONE_CREATED,
  COMM_PROJECT_MILESTONE_COMPLETED,
] as const;
