// ─── Workflow Events ──────────────────────────────────────────────────────────

export const COMM_WORKFLOW_CREATED = "COMM.WORKFLOW_CREATED" as const;
export const COMM_WORKFLOW_UPDATED = "COMM.WORKFLOW_UPDATED" as const;
export const COMM_WORKFLOW_STATUS_CHANGED = "COMM.WORKFLOW_STATUS_CHANGED" as const;
export const COMM_WORKFLOW_DELETED = "COMM.WORKFLOW_DELETED" as const;
export const COMM_WORKFLOW_TRIGGERED = "COMM.WORKFLOW_TRIGGERED" as const;
export const COMM_WORKFLOW_RUN_COMPLETED = "COMM.WORKFLOW_RUN_COMPLETED" as const;
export const COMM_WORKFLOW_RUN_FAILED = "COMM.WORKFLOW_RUN_FAILED" as const;

export const WorkflowEventTypes = [
  COMM_WORKFLOW_CREATED,
  COMM_WORKFLOW_UPDATED,
  COMM_WORKFLOW_STATUS_CHANGED,
  COMM_WORKFLOW_DELETED,
  COMM_WORKFLOW_TRIGGERED,
  COMM_WORKFLOW_RUN_COMPLETED,
  COMM_WORKFLOW_RUN_FAILED,
] as const;
