export const COMM_CHATTER_MESSAGE_POSTED = "COMM.CHATTER_MESSAGE_POSTED" as const;
export const COMM_CHATTER_MESSAGE_UPDATED = "COMM.CHATTER_MESSAGE_UPDATED" as const;
export const COMM_CHATTER_MESSAGE_DELETED = "COMM.CHATTER_MESSAGE_DELETED" as const;

export const ChatterEventTypes = [
  COMM_CHATTER_MESSAGE_POSTED,
  COMM_CHATTER_MESSAGE_UPDATED,
  COMM_CHATTER_MESSAGE_DELETED,
] as const;
