/**
 * Treasury error codes.
 *
 * RULES:
 *   1. All codes prefixed with TREAS_, TREASURY_, or TRY_
 *   2. Naming convention: TREAS_NOUN_REASON (SCREAMING_SNAKE_CASE)
 *   3. Removing or renaming a code is a BREAKING CHANGE
 */
import { z } from "zod";

// ─── Treasury Bank Account Error Codes ────────────────────────────────────────
export const TREAS_BANK_ACCOUNT_NOT_FOUND = "TREAS_BANK_ACCOUNT_NOT_FOUND" as const;
export const TREAS_BANK_ACCOUNT_INACTIVE = "TREAS_BANK_ACCOUNT_INACTIVE" as const;
export const TREAS_BANK_ACCOUNT_SUSPENDED = "TREAS_BANK_ACCOUNT_SUSPENDED" as const;
export const TREAS_BANK_ACCOUNT_NUMBER_EXISTS = "TREAS_BANK_ACCOUNT_NUMBER_EXISTS" as const;

// ─── Treasury Bank Statement Error Codes ──────────────────────────────────────
export const TREAS_BANK_STATEMENT_NOT_FOUND = "TREAS_BANK_STATEMENT_NOT_FOUND" as const;
export const TREAS_BANK_STATEMENT_ALREADY_INGESTED =
  "TREAS_BANK_STATEMENT_ALREADY_INGESTED" as const;
export const TREAS_BANK_STATEMENT_PROCESSING_FAILED =
  "TREAS_BANK_STATEMENT_PROCESSING_FAILED" as const;

// ─── Treasury Reconciliation Error Codes ──────────────────────────────────────
export const TREAS_RECONCILIATION_SESSION_NOT_FOUND =
  "TREAS_RECONCILIATION_SESSION_NOT_FOUND" as const;
export const TREAS_RECONCILIATION_SESSION_CLOSED = "TREAS_RECONCILIATION_SESSION_CLOSED" as const;
export const TREAS_RECONCILIATION_SESSION_VOIDED = "TREAS_RECONCILIATION_SESSION_VOIDED" as const;
export const TREAS_RECONCILIATION_MATCH_EXCEEDS_LINE_AMOUNT =
  "TREAS_RECONCILIATION_MATCH_EXCEEDS_LINE_AMOUNT" as const;
export const TREAS_RECONCILIATION_LINE_ALREADY_MATCHED =
  "TREAS_RECONCILIATION_LINE_ALREADY_MATCHED" as const;
export const TREAS_RECONCILIATION_MATCH_NOT_FOUND = "TREAS_RECONCILIATION_MATCH_NOT_FOUND" as const;

// ─── Treasury Payment Batch Error Codes ───────────────────────────────────────
export const TREAS_PAYMENT_BATCH_NOT_FOUND = "TREAS_PAYMENT_BATCH_NOT_FOUND" as const;
export const TREAS_PAYMENT_BATCH_NOT_DRAFT = "TREAS_PAYMENT_BATCH_NOT_DRAFT" as const;
export const TREAS_PAYMENT_BATCH_ALREADY_APPROVED = "TREAS_PAYMENT_BATCH_ALREADY_APPROVED" as const;
export const TREAS_PAYMENT_BATCH_ALREADY_RELEASED = "TREAS_PAYMENT_BATCH_ALREADY_RELEASED" as const;
export const TREAS_PAYMENT_BATCH_CANCELLED = "TREAS_PAYMENT_BATCH_CANCELLED" as const;
export const TREAS_PAYMENT_BATCH_EMPTY = "TREAS_PAYMENT_BATCH_EMPTY" as const;
export const TREAS_PAYMENT_BATCH_DIMENSION_MISMATCH =
  "TREAS_PAYMENT_BATCH_DIMENSION_MISMATCH" as const;
export const TREAS_PAYMENT_BATCH_ILLEGAL_TRANSITION =
  "TREAS_PAYMENT_BATCH_ILLEGAL_TRANSITION" as const;
export const TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_FOUND =
  "TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_FOUND" as const;
export const TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_APPROVED =
  "TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_APPROVED" as const;

// ─── Treasury Payment Instruction Error Codes ─────────────────────────────────
export const TREAS_PAYMENT_INSTRUCTION_NOT_FOUND = "TREAS_PAYMENT_INSTRUCTION_NOT_FOUND" as const;
export const TREAS_PAYMENT_INSTRUCTION_AMOUNT_MISMATCH =
  "TREAS_PAYMENT_INSTRUCTION_AMOUNT_MISMATCH" as const;
export const TREAS_PAYMENT_INSTRUCTION_BANK_ACCOUNT_MISSING =
  "TREAS_PAYMENT_INSTRUCTION_BANK_ACCOUNT_MISSING" as const;
export const TREAS_PAYMENT_INSTRUCTION_ILLEGAL_TRANSITION =
  "TREAS_PAYMENT_INSTRUCTION_ILLEGAL_TRANSITION" as const;
export const TREAS_PAYMENT_INSTRUCTION_INVALID_BANK_ACCOUNT =
  "TREAS_PAYMENT_INSTRUCTION_INVALID_BANK_ACCOUNT" as const;

// ─── Treasury SOD Error Codes ─────────────────────────────────────────────────
export const TREAS_PAYMENT_SOD_VIOLATION = "TREAS_PAYMENT_SOD_VIOLATION" as const;

// ─── Treasury Liquidity & Forecasting Error Codes ─────────────────────────────
export const TREASURY_LIQUIDITY_SOURCE_FEED_NOT_FOUND =
  "TREASURY_LIQUIDITY_SOURCE_FEED_NOT_FOUND" as const;
export const TREASURY_AP_DUE_PAYMENT_PROJECTION_NOT_FOUND =
  "TREASURY_AP_DUE_PAYMENT_PROJECTION_NOT_FOUND" as const;
export const TREASURY_AR_EXPECTED_RECEIPT_PROJECTION_NOT_FOUND =
  "TREASURY_AR_EXPECTED_RECEIPT_PROJECTION_NOT_FOUND" as const;
export const TREASURY_FORECAST_VARIANCE_NOT_FOUND = "TREASURY_FORECAST_VARIANCE_NOT_FOUND" as const;
export const TREASURY_FX_NORMALIZATION_REQUIRED = "TREASURY_FX_NORMALIZATION_REQUIRED" as const;
export const TREASURY_FX_RATE_SNAPSHOT_NOT_FOUND = "TREASURY_FX_RATE_SNAPSHOT_NOT_FOUND" as const;
export const TREASURY_LIQUIDITY_FORECAST_BUCKET_NOT_FOUND =
  "TREASURY_LIQUIDITY_FORECAST_BUCKET_NOT_FOUND" as const;

// ─── Treasury Internal Banking Error Codes ────────────────────────────────────
export const TREASURY_INTERNAL_BANK_ACCOUNT_NOT_FOUND =
  "TREASURY_INTERNAL_BANK_ACCOUNT_NOT_FOUND" as const;
export const TREASURY_INTERNAL_BANK_ACCOUNT_CODE_EXISTS =
  "TREASURY_INTERNAL_BANK_ACCOUNT_CODE_EXISTS" as const;
export const TREASURY_INTERNAL_BANK_ACCOUNT_ILLEGAL_TRANSITION =
  "TREASURY_INTERNAL_BANK_ACCOUNT_ILLEGAL_TRANSITION" as const;

// ─── Treasury Intercompany Transfer Error Codes ───────────────────────────────
export const TREASURY_INTERCOMPANY_TRANSFER_NOT_FOUND =
  "TREASURY_INTERCOMPANY_TRANSFER_NOT_FOUND" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_NUMBER_EXISTS =
  "TREASURY_INTERCOMPANY_TRANSFER_NUMBER_EXISTS" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_SAME_ENTITY =
  "TREASURY_INTERCOMPANY_TRANSFER_SAME_ENTITY" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_NOT_FOUND =
  "TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_NOT_FOUND" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_INACTIVE =
  "TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_INACTIVE" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_ENTITY_ACCOUNT_MISMATCH =
  "TREASURY_INTERCOMPANY_TRANSFER_ENTITY_ACCOUNT_MISMATCH" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_CURRENCY_MISMATCH =
  "TREASURY_INTERCOMPANY_TRANSFER_CURRENCY_MISMATCH" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_DEBIT_MISMATCH =
  "TREASURY_INTERCOMPANY_TRANSFER_DEBIT_MISMATCH" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_CREDIT_MISMATCH =
  "TREASURY_INTERCOMPANY_TRANSFER_CREDIT_MISMATCH" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_UNBALANCED =
  "TREASURY_INTERCOMPANY_TRANSFER_UNBALANCED" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_ILLEGAL_TRANSITION =
  "TREASURY_INTERCOMPANY_TRANSFER_ILLEGAL_TRANSITION" as const;
export const TREASURY_INTERCOMPANY_TRANSFER_SOD_VIOLATION =
  "TREASURY_INTERCOMPANY_TRANSFER_SOD_VIOLATION" as const;

// ─── Legacy TRY_ Prefix Error Codes ───────────────────────────────────────────
export const TRY_BANK_ACCOUNT_NOT_FOUND = "TRY_BANK_ACCOUNT_NOT_FOUND" as const;
export const TRY_BANK_ACCOUNT_ALREADY_EXISTS = "TRY_BANK_ACCOUNT_ALREADY_EXISTS" as const;
export const TRY_BANK_ACCOUNT_INACTIVE = "TRY_BANK_ACCOUNT_INACTIVE" as const;
export const TRY_BANK_STATEMENT_NOT_FOUND = "TRY_BANK_STATEMENT_NOT_FOUND" as const;
export const TRY_BANK_STATEMENT_DUPLICATE = "TRY_BANK_STATEMENT_DUPLICATE" as const;
export const TRY_BANK_STATEMENT_INGESTION_FAILED = "TRY_BANK_STATEMENT_INGESTION_FAILED" as const;
export const TRY_RECONCILIATION_SESSION_NOT_FOUND = "TRY_RECONCILIATION_SESSION_NOT_FOUND" as const;
export const TRY_RECONCILIATION_SESSION_ALREADY_CLOSED =
  "TRY_RECONCILIATION_SESSION_ALREADY_CLOSED" as const;
export const TRY_PAYMENT_BATCH_NOT_FOUND = "TRY_PAYMENT_BATCH_NOT_FOUND" as const;
export const TRY_PAYMENT_BATCH_ALREADY_RELEASED = "TRY_PAYMENT_BATCH_ALREADY_RELEASED" as const;
export const TRY_PAYMENT_INSTRUCTION_NOT_FOUND = "TRY_PAYMENT_INSTRUCTION_NOT_FOUND" as const;

// ─── Treasury Error Code Array ────────────────────────────────────────────────
export const TreasuryErrorCodeValues = [
  // Bank Accounts
  TREAS_BANK_ACCOUNT_NOT_FOUND,
  TREAS_BANK_ACCOUNT_INACTIVE,
  TREAS_BANK_ACCOUNT_SUSPENDED,
  TREAS_BANK_ACCOUNT_NUMBER_EXISTS,

  // Bank Statements
  TREAS_BANK_STATEMENT_NOT_FOUND,
  TREAS_BANK_STATEMENT_ALREADY_INGESTED,
  TREAS_BANK_STATEMENT_PROCESSING_FAILED,

  // Reconciliation
  TREAS_RECONCILIATION_SESSION_NOT_FOUND,
  TREAS_RECONCILIATION_SESSION_CLOSED,
  TREAS_RECONCILIATION_SESSION_VOIDED,
  TREAS_RECONCILIATION_MATCH_EXCEEDS_LINE_AMOUNT,
  TREAS_RECONCILIATION_LINE_ALREADY_MATCHED,
  TREAS_RECONCILIATION_MATCH_NOT_FOUND,

  // Payment Batches
  TREAS_PAYMENT_BATCH_NOT_FOUND,
  TREAS_PAYMENT_BATCH_NOT_DRAFT,
  TREAS_PAYMENT_BATCH_ALREADY_APPROVED,
  TREAS_PAYMENT_BATCH_ALREADY_RELEASED,
  TREAS_PAYMENT_BATCH_CANCELLED,
  TREAS_PAYMENT_BATCH_EMPTY,
  TREAS_PAYMENT_BATCH_DIMENSION_MISMATCH,
  TREAS_PAYMENT_BATCH_ILLEGAL_TRANSITION,
  TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_FOUND,
  TREAS_PAYMENT_BATCH_INSTRUCTION_NOT_APPROVED,

  // Payment Instructions
  TREAS_PAYMENT_INSTRUCTION_NOT_FOUND,
  TREAS_PAYMENT_INSTRUCTION_AMOUNT_MISMATCH,
  TREAS_PAYMENT_INSTRUCTION_BANK_ACCOUNT_MISSING,
  TREAS_PAYMENT_INSTRUCTION_ILLEGAL_TRANSITION,
  TREAS_PAYMENT_INSTRUCTION_INVALID_BANK_ACCOUNT,

  // SOD
  TREAS_PAYMENT_SOD_VIOLATION,

  // Liquidity & Forecasting
  TREASURY_LIQUIDITY_SOURCE_FEED_NOT_FOUND,
  TREASURY_AP_DUE_PAYMENT_PROJECTION_NOT_FOUND,
  TREASURY_AR_EXPECTED_RECEIPT_PROJECTION_NOT_FOUND,
  TREASURY_FORECAST_VARIANCE_NOT_FOUND,
  TREASURY_FX_NORMALIZATION_REQUIRED,
  TREASURY_FX_RATE_SNAPSHOT_NOT_FOUND,
  TREASURY_LIQUIDITY_FORECAST_BUCKET_NOT_FOUND,

  // Internal Banking
  TREASURY_INTERNAL_BANK_ACCOUNT_NOT_FOUND,
  TREASURY_INTERNAL_BANK_ACCOUNT_CODE_EXISTS,
  TREASURY_INTERNAL_BANK_ACCOUNT_ILLEGAL_TRANSITION,

  // Intercompany Transfers
  TREASURY_INTERCOMPANY_TRANSFER_NOT_FOUND,
  TREASURY_INTERCOMPANY_TRANSFER_NUMBER_EXISTS,
  TREASURY_INTERCOMPANY_TRANSFER_SAME_ENTITY,
  TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_NOT_FOUND,
  TREASURY_INTERCOMPANY_TRANSFER_ACCOUNT_INACTIVE,
  TREASURY_INTERCOMPANY_TRANSFER_ENTITY_ACCOUNT_MISMATCH,
  TREASURY_INTERCOMPANY_TRANSFER_CURRENCY_MISMATCH,
  TREASURY_INTERCOMPANY_TRANSFER_DEBIT_MISMATCH,
  TREASURY_INTERCOMPANY_TRANSFER_CREDIT_MISMATCH,
  TREASURY_INTERCOMPANY_TRANSFER_UNBALANCED,
  TREASURY_INTERCOMPANY_TRANSFER_ILLEGAL_TRANSITION,
  TREASURY_INTERCOMPANY_TRANSFER_SOD_VIOLATION,

  // Legacy TRY_ prefix
  TRY_BANK_ACCOUNT_NOT_FOUND,
  TRY_BANK_ACCOUNT_ALREADY_EXISTS,
  TRY_BANK_ACCOUNT_INACTIVE,
  TRY_BANK_STATEMENT_NOT_FOUND,
  TRY_BANK_STATEMENT_DUPLICATE,
  TRY_BANK_STATEMENT_INGESTION_FAILED,
  TRY_RECONCILIATION_SESSION_NOT_FOUND,
  TRY_RECONCILIATION_SESSION_ALREADY_CLOSED,
  TRY_PAYMENT_BATCH_NOT_FOUND,
  TRY_PAYMENT_BATCH_ALREADY_RELEASED,
  TRY_PAYMENT_INSTRUCTION_NOT_FOUND,
] as const;

export const TreasuryErrorCodeSchema = z.enum(TreasuryErrorCodeValues);
export type TreasuryErrorCode = z.infer<typeof TreasuryErrorCodeSchema>;
