/**
 * /admin — Observability overview.
 *
 * Shows quick-reference for what you can DO with the OTel integration,
 * links to Jaeger, semantic attribute reference, and live API health.
 */

const JAEGER_UI = process.env.NEXT_PUBLIC_JAEGER_UI ?? "http://localhost:16686";
const API_URL   = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";

const ATTR_DOCS = [
  { key: "afenda.org.id",          source: "Auto — from every request's org context" },
  { key: "afenda.org.slug",        source: "Auto — from subdomain / X-Org-Id header" },
  { key: "afenda.principal.id",    source: "Auto — from authenticated user context" },
  { key: "afenda.correlation.id",  source: "Auto — from X-Correlation-Id header or generated UUID" },
  { key: "afenda.idempotency.key", source: "Auto — from service params.idempotencyKey" },
  { key: "afenda.error.code",      source: "Auto — from { ok: false, error: { code } } results" },
] as const;

const SPAN_EXAMPLES = [
  { name: "ap.submit_invoice",         desc: "Submit a new invoice → draft → submitted" },
  { name: "ap.approve_invoice",        desc: "Approve an invoice (SoD enforced)" },
  { name: "ap.reject_invoice",         desc: "Reject an invoice with reason" },
  { name: "ap.void_invoice",           desc: "Void an invoice" },
  { name: "ap.mark_paid",              desc: "Mark invoice as paid (posted → paid)" },
  { name: "ap.list_invoices",          desc: "Cursor-paginated invoice listing" },
  { name: "gl.post_to_gl",             desc: "Post balanced journal entry" },
  { name: "gl.reverse_journal_entry",  desc: "Reverse a journal entry (debit↔credit swap)" },
  { name: "gl.get_trial_balance",      desc: "Trial balance query" },
  { name: "evidence.register_document", desc: "Register uploaded document metadata" },
  { name: "evidence.attach_evidence",   desc: "Link evidence to an entity" },
] as const;

const USEFUL_QUERIES = [
  {
    label: "All traces for an org",
    url: `${JAEGER_UI}/search?service=afenda-api&tags=%7B%22afenda.org.id%22%3A%22YOUR_ORG_ID%22%7D`,
  },
  {
    label: "All invoice submissions",
    url: `${JAEGER_UI}/search?service=afenda-api&operation=ap.submit_invoice`,
  },
  {
    label: "Domain errors only",
    url: `${JAEGER_UI}/search?service=afenda-api&tags=%7B%22afenda.error.code%22%3A%22AP_INVOICE_NOT_FOUND%22%7D`,
  },
  {
    label: "Slow queries (> 500ms)",
    url: `${JAEGER_UI}/search?service=afenda-api&minDuration=500ms`,
  },
  {
    label: "Failed HTTP requests",
    url: `${JAEGER_UI}/search?service=afenda-api&tags=%7B%22http.response.status_code%22%3A500%7D`,
  },
] as const;

export default function AdminOverview() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8 space-y-10">
      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Observability</h1>
        <p className="text-sm text-muted-foreground mt-1">
          OpenTelemetry auto-instrumentation is active. Every domain service call
          produces a span in Jaeger with business context auto-derived from
          function names and argument shapes.
        </p>
      </div>

      {/* ── Quick links ────────────────────────────────────────────────────── */}
      <section className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card
          title="Jaeger UI"
          description="Full trace search, timeline, DAG"
          href={JAEGER_UI}
        />
        <Card
          title="Embedded Traces"
          description="Jaeger inside this app"
          href="/admin/traces"
          internal
        />
        <Card
          title="API Health"
          description="/readyz — DB + migration status"
          href={`${API_URL}/readyz`}
        />
      </section>

      {/* ── Auto-generated spans ───────────────────────────────────────────── */}
      <section>
        <h2 className="text-lg font-semibold mb-3">Auto-instrumented spans</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Generated by <code className="text-xs bg-surface-100 px-1.5 py-0.5 rounded">instrumentService(namespace, fns)</code>
          — add a new service function and its span appears automatically.
        </p>
        <div className="border rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-surface-100 text-left">
              <tr>
                <th className="px-4 py-2 font-medium">Span Name</th>
                <th className="px-4 py-2 font-medium">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {SPAN_EXAMPLES.map((s) => (
                <tr key={s.name} className="hover:bg-overlay-hover">
                  <td className="px-4 py-2 font-mono text-xs">{s.name}</td>
                  <td className="px-4 py-2 text-muted-foreground">{s.desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── Semantic attributes ────────────────────────────────────────────── */}
      <section>
        <h2 className="text-lg font-semibold mb-3">Semantic attributes</h2>
        <p className="text-sm text-muted-foreground mb-4">
          All attributes are auto-extracted by duck-typing function arguments
          at call time — no manual annotation. Searchable in Jaeger.
        </p>
        <div className="border rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-surface-100 text-left">
              <tr>
                <th className="px-4 py-2 font-medium">Attribute</th>
                <th className="px-4 py-2 font-medium">Source</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {ATTR_DOCS.map((a) => (
                <tr key={a.key} className="hover:bg-overlay-hover">
                  <td className="px-4 py-2 font-mono text-xs">{a.key}</td>
                  <td className="px-4 py-2 text-muted-foreground">{a.source}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── Useful Jaeger queries ──────────────────────────────────────────── */}
      <section>
        <h2 className="text-lg font-semibold mb-3">Useful Jaeger queries</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Ready-made searches to answer common questions.
        </p>
        <ul className="space-y-2">
          {USEFUL_QUERIES.map((q) => (
            <li key={q.label}>
              <a
                href={q.url}
                target="_blank"
                rel="noreferrer"
                className="text-sm text-primary hover:underline"
              >
                {q.label} ↗
              </a>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}

// ── Card component ───────────────────────────────────────────────────────────

function Card({
  title,
  description,
  href,
  internal,
}: {
  title: string;
  description: string;
  href: string;
  internal?: boolean;
}) {
  return (
    <a
      href={href}
      target={internal ? undefined : "_blank"}
      rel={internal ? undefined : "noreferrer"}
      className="border rounded-lg p-4 hover:border-primary hover:shadow-sm transition-all group"
    >
      <h3 className="font-medium group-hover:text-primary">
        {title}
      </h3>
      <p className="text-xs text-muted-foreground mt-1">{description}</p>
    </a>
  );
}
