export const COMM_TASK_CHECKLIST_ITEM_ADDED = "COMM.TASK_CHECKLIST_ITEM_ADDED" as const;
export const COMM_TASK_CHECKLIST_ITEM_TOGGLED = "COMM.TASK_CHECKLIST_ITEM_TOGGLED" as const;
export const COMM_TASK_CHECKLIST_ITEM_REMOVED = "COMM.TASK_CHECKLIST_ITEM_REMOVED" as const;
export const COMM_TASK_CHECKLIST_UPDATED = "COMM.TASK_CHECKLIST_UPDATED" as const;
