export const COMM_TASK_TIME_ENTRY_CREATED = "COMM.TASK_TIME_ENTRY_CREATED" as const;
export const COMM_TASK_TIME_ENTRY_UPDATED = "COMM.TASK_TIME_ENTRY_UPDATED" as const;
export const COMM_TASK_TIME_ENTRY_DELETED = "COMM.TASK_TIME_ENTRY_DELETED" as const;
