export const COMM_ANNOUNCEMENT_PUBLISHED = "COMM.ANNOUNCEMENT_PUBLISHED" as const;
export const COMM_ANNOUNCEMENT_SCHEDULED = "COMM.ANNOUNCEMENT_SCHEDULED" as const;
export const COMM_ANNOUNCEMENT_ACKNOWLEDGED = "COMM.ANNOUNCEMENT_ACKNOWLEDGED" as const;
export const COMM_ANNOUNCEMENT_ARCHIVED = "COMM.ANNOUNCEMENT_ARCHIVED" as const;
export const COMM_ANNOUNCEMENT_CREATED = "COMM.ANNOUNCEMENT_CREATED" as const;
