import type { Metadata } from "next";
import Link from "next/link";
import { Shield, Cpu } from "lucide-react";

import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@afenda/ui";

export const revalidate = 2592000; // monthly ISR

export const metadata: Metadata = {
  title: "Privacy Policy — AFENDA",
  description:
    "Privacy policy, data protection, and security practices. SOC 2 Type II, HIPAA, GDPR, and CCPA compliance.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "Privacy Policy — AFENDA",
    description:
      "Enterprise privacy policy with SOC 2 Type II, HIPAA, GDPR, and CCPA compliance.",
    type: "website",
    url: "/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-16">
      <div className="w-full">
        <Card>
          <CardHeader className="space-y-3 text-center">
            <CardTitle className="text-2xl">Privacy Policy</CardTitle>
            <CardDescription>
              Enterprise-grade privacy commitments powered by NexusCanon.
            </CardDescription>
            <div className="flex flex-wrap justify-center gap-2">
              <Badge variant="outline" className="gap-1">
                <Shield className="h-3 w-3" aria-hidden="true" /> SOC 2 Type II
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Shield className="h-3 w-3" aria-hidden="true" /> HIPAA BAA
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Shield className="h-3 w-3" aria-hidden="true" /> GDPR + CCPA
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Cpu className="h-3 w-3" aria-hidden="true" /> NexusCanon
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="grid gap-8">
            <section className="grid gap-4 md:grid-cols-3">
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">We Do Not Sell Data</h3>
                <p className="text-muted-foreground mt-2">
                  Personal data is never sold or monetized. Processing is
                  limited to service delivery and compliance needs.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Military-Grade Encryption</h3>
                <p className="text-muted-foreground mt-2">
                  AES-256-GCM encryption at rest, TLS 1.3 in transit, and
                  hardware-backed key management protect all data layers.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Retention Controls</h3>
                <p className="text-muted-foreground mt-2">
                  Account data is retained while active and removed within 30
                  days after closure, subject to legal obligations.
                </p>
              </div>
            </section>

            <div className="space-y-4 text-sm">
              <section>
                <h3 className="font-semibold">Information We Collect</h3>
                <p className="text-muted-foreground">
                  We collect information you provide directly (such as account
                  details and support requests) and information generated by
                  service usage (such as audit logs and operational metadata).
                  All data is stored securely with encryption controls.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">
                  Data Storage &amp; Infrastructure
                </h3>
                <p className="text-muted-foreground">
                  Your data is powered by{" "}
                  <strong>NexusCanon Infrastructure Fabric</strong> in the{" "}
                  <strong>ap-southeast-1 (Singapore)</strong> region. Our
                  infrastructure is SOC 2 Type II certified, HIPAA compliant,
                  and features:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>
                    <strong>Military-grade encryption:</strong> AES-256-GCM at
                    rest, TLS 1.3 in transit
                  </li>
                  <li>
                    <strong>Continuous protection:</strong> Hourly snapshots with
                    30-day point-in-time recovery
                  </li>
                  <li>
                    <strong>High availability:</strong> Multi-AZ deployment with
                    automatic failover
                  </li>
                  <li>
                    <strong>Branch-first safety:</strong> Instant copy-on-write
                    database branches
                  </li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">
                  How We Use Your Information
                </h3>
                <p className="text-muted-foreground">
                  We use collected information to deliver and operate the
                  service, maintain security, improve performance, respond to
                  support requests, and meet legal or compliance requirements.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Legal Bases for Processing</h3>
                <p className="text-muted-foreground">
                  Where applicable, we process data based on contractual
                  necessity, legitimate interests in operating a secure
                  platform, compliance with legal obligations, and user consent
                  when required.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Information Sharing</h3>
                <p className="text-muted-foreground">
                  We do not sell personal information. We share data only with
                  vetted subprocessors required to operate the service:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>
                    <strong>NexusCanon Infrastructure:</strong> Core database
                    engine (SOC 2 Type II, HIPAA, GDPR)
                  </li>
                  <li>
                    <strong>Authentication Services:</strong> OAuth 2.0 and
                    JWT-based identity management
                  </li>
                  <li>
                    <strong>Cloud Infrastructure:</strong> Multi-region compute
                    and storage providers
                  </li>
                  <li>
                    <strong>CDN &amp; Edge:</strong> Global content delivery and
                    DDoS protection
                  </li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">Data Security</h3>
                <p className="text-muted-foreground">
                  We implement layered security controls, including:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>
                    <strong>Encryption:</strong> AES-256-GCM at rest, TLS 1.3 in
                    transit, hardware-backed key management
                  </li>
                  <li>
                    <strong>Authentication:</strong> OAuth 2.0 with short-lived
                    JWT tokens
                  </li>
                  <li>
                    <strong>Access Control:</strong> Zero-trust RBAC, row-level
                    security (RLS), and policy-based isolation
                  </li>
                  <li>
                    <strong>Audit Logging:</strong> 365-day retention with
                    immutable audit trails and compliance reporting
                  </li>
                  <li>
                    <strong>Backup &amp; Recovery:</strong> Hourly snapshots,
                    30-day PITR, cross-region replication
                  </li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">
                  Your Rights (GDPR &amp; CCPA)
                </h3>
                <p className="text-muted-foreground">You have the right to:</p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>
                    <strong>Access:</strong> Request a copy of your personal data
                  </li>
                  <li>
                    <strong>Rectification:</strong> Update or correct your
                    information
                  </li>
                  <li>
                    <strong>Erasure:</strong> Request deletion of your data
                    (&quot;right to be forgotten&quot;)
                  </li>
                  <li>
                    <strong>Portability:</strong> Export your data in a
                    machine-readable format
                  </li>
                  <li>
                    <strong>Objection:</strong> Opt-out of certain data
                    processing activities
                  </li>
                </ul>
                <p className="text-muted-foreground mt-2">
                  Contact{" "}
                  <a
                    href="mailto:legal@nexuscanon.com"
                    className="underline"
                  >
                    legal@nexuscanon.com
                  </a>{" "}
                  to exercise your rights.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Data Retention</h3>
                <p className="text-muted-foreground">
                  We retain your data for as long as your account is active or
                  as needed to provide services. Deleted data is securely purged
                  within 30 days using cryptographic erasure. Audit logs are
                  retained for 365 days for compliance and forensic purposes.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">
                  Compliance &amp; Certifications
                </h3>
                <p className="text-muted-foreground">
                  Our infrastructure meets the following standards:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>
                    <strong>SOC 2 Type II:</strong> Annual third-party audit
                  </li>
                  <li>
                    <strong>HIPAA:</strong> Business Associate Agreement (BAA)
                    available
                  </li>
                  <li>
                    <strong>GDPR:</strong> Full EU data protection compliance
                  </li>
                  <li>
                    <strong>CCPA:</strong> California Consumer Privacy Act
                    compliance
                  </li>
                  <li>
                    <strong>ISO 27001:</strong> Information security management
                    (in progress)
                  </li>
                </ul>
              </section>
            </div>

            <div className="flex flex-col gap-2">
              <Link
                href="/cookie-policy"
                className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
              >
                Cookie Policy
              </Link>
              <Link
                href="/terms"
                className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
              >
                Terms of Service
              </Link>
              <Link
                href="/sla"
                className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
              >
                SLA
              </Link>
              <Link
                href="/pdpa"
                className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
              >
                PDPA Compliance
              </Link>
              <Link
                href="/"
                className="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground"
              >
                Back to Home
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
